Small mistake in the path for FileChooser
hunkanome/AGILE-KroustyTour pull request #29
Opened 2023-12-05 17:06 UTC by AdriMerle

2023-12-05 17:33 UTC, mart-84 requested changes

2023-12-05 17:33 UTC, mart-84 commented on src/main/java/fr/insalyon/controller/MainController.java
> +		String userDirectoryString = System.getProperty("user.dir") + "/data/xml";
Pourquoi forcément dans data/xml ? Il n'existe pas forcément sur la machine de l'utilisateur.
Un répertoire plus général, type home de l'utilisateur, me parait plus approprié

2023-12-05 18:33 UTC, AdriMerle commented on src/main/java/fr/insalyon/controller/MainController.java
> +		String userDirectoryString = System.getProperty("user.dir") + "/data/xml";
L'idée c'était de faire en sorte d'arriver dans ce dossier par défaut (dans notre cas ce sera le plus utile). Dans tous les cas, ça veut juste dire que par défaut on arrive dans ce dossier, mais on peut très bien en changer derrière. Mais si vous pensez que c'est mieux comme ça on remet ce qu'il y avait de base

2023-12-05 19:36 UTC, mart-84 commented on src/main/java/fr/insalyon/controller/MainController.java
> +		String userDirectoryString = System.getProperty("user.dir") + "/data/xml";
Justement, on sait pas si le répertoire existe sur la machine.
Tu as peut être fait ça juste pour le dev, pour éviter 2 clics. C'est une mauvaise idée de faire un petit truc comme ça juste pour le dev, c'est le genre de chose qu'on oublie de changer.
Donc autant mettre directement une bonne valeur. Par exemple `user.home` permet d'avoir directement le répertoire de l'utilisateur, ce qui est plus cohérent

2023-12-06 07:27 UTC, ant0-sb approved these changes

2023-12-06 07:28 UTC, merged